#!/bin/bash
# MoAI Statusline Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai statusline command.
# Paths are configured during project initialization.

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH first
if command -v moai &> /dev/null; then
	exec moai statusline < "$temp_file"
fi

# Try detected Go bin path from initialization
if [ -f "C:/Users/ycr01/go/bin/moai" ]; then
	exec "C:/Users/ycr01/go/bin/moai" statusline < "$temp_file"
fi

# Try user local bin directory
if [ -f "C:/Users/ycr01/.local/bin/moai" ]; then
	exec "C:/Users/ycr01/.local/bin/moai" statusline < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing statusline gracefully)
exit 0
